### ISSUE TITLE
Incorrect SQL formatting (missing spaces)

### ISSUE THREAD

**Issue by roberthunt** [sniffy/sniffy#182]
I couldn't see this reported anywhere, I'm experiencing missing spaces in my query output (the queries are executing fine, it's just the display formatting). I haven't had chance to produce a demo project yet but I thought I'd report it before I forget in case it's something easy to spot.

I'm using QueryDSL 4.1.1 which is responsible for generating the SQL so I don't know if it's related to that in this case.

![formatting](https://cloud.githubusercontent.com/assets/567676/15690197/5a743e46-277a-11e6-93d7-0a526a00fe47.png)

Thanks!

**Comment by bedrin** [comment]
Not reproducible. Probably have been solved automatically with the update of some of the libraries.
Closing in 3.1.3

**Comment by roberthunt** [comment]
Hey @bedrin I've managed to put together a demo project for this issue as it's still present in 3.1.3 https://github.com/roberthunt/sniffy-querydsl

It looks like it's specific to using QueryDSL (with the native SQL module rather than JPA module)

The logged query seems fine:
![screen shot 2017-03-30 at 12 07 17](https://cloud.githubusercontent.com/assets/567676/24501509/b330fb72-1541-11e7-828f-a9f479edd248.png)

But Sniffy prints it slightly differently:
![screen shot 2017-03-30 at 12 07 55](https://cloud.githubusercontent.com/assets/567676/24501529/c11d1342-1541-11e7-8925-03277cefb5f3.png)

Let me know if you need any more info.

**Comment by roberthunt** [comment]
A quick look at the debugger shows QueryDSL is inserting newline characters "\n" between parts of the statement which seems to be the cause of this problem. Maybe it's just a case of normalising the statement to remove these sorts of characters?

![screen shot 2017-03-30 at 12 48 09](https://cloud.githubusercontent.com/assets/567676/24502797/34d10afa-1547-11e7-94f8-1fb42f3e955f.png)

**Comment by bedrin** [comment]
Wow! Thanks for investigation - will fix it 3.1.4

**Comment by roberthunt** [comment]
I've just done a bit more digging and discovered that [QueryDSL has a way to disable this newline behaviour](https://groups.google.com/forum/#!topic/querydsl/Zj9cTZz0Y5o) by customising the SQLTemplate:

`SQLTemplates templates = MySQLTemplates.builder().newLineToSingleSpace().build();`

This appears to fix the issue so it's your call if you want to bother handling it in Sniffy at all.

**Comment by bedrin** [comment]
Fixed in 3.1.4
